# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('cm', models.IntegerField(default=0)),
                ('inch', models.IntegerField(default=0)),
                ('sensorDate', models.CharField(max_length=99999999)),
            ],
        ),
    ]
