# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('v_0_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.CharField(default=datetime.datetime(2016, 3, 2, 7, 56, 20, 426000, tzinfo=utc), max_length=99999999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='sensorDate',
            field=models.CharField(default=b' ', max_length=99999999),
        ),
    ]
