# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_0_1', '0002_auto_20160302_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.CharField(default=b' ', max_length=99999999),
        ),
    ]
