# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_0_1', '0003_auto_20160302_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='firstLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='secondLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='thirdLevel',
            field=models.IntegerField(default=0),
        ),
    ]
